language: node_js
node_js:
- 8

branches:
  only:
  - master
  - develop
  - angular

cache:
  directories:
  - node_modules

before_script:
- npm install -g @angular/cli

script:
- ng lint
- ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/taptab
  on:
    branch: angular

notifications:
  email:
    on_failure: never
    on_success: never
