sudo: required
addons:
  chrome: stable

language: node_js
node_js:
- 8
- 9

branches:
  only:
  - master
  - develop
  - angular

cache:
  directories:
  - node_modules

before_script:
- npm install -g @angular/cli

script:
- ng lint
- ng test --watch=false
- ng build --prod

notifications:
  email:
    on_failure: never
    on_success: never

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/taptab
  on:
    branch: angular
